### ISSUE TITLE
[GalacticScale] [Bug] Crash at game start if no suitable starting planet

### ISSUE THREAD

**Issue by bzy-xyz** [Touhma/DSP_Plugins#10]
Sometimes when generating a new galaxy there is no suitable planet created in star system 0 to be selected as a 'birth planet' by `UniverseGen::CreateGalaxy`. This causes a crash at initialization as the `GuideMissionStandardMode` falls over due to being handed a null `localPlanet`.

```
NullReferenceException: Object reference not set to an instance of an object
  at GuideMissionStandardMode.Init (.GameData _gameData) [0x00000] in <filename unknown>:0 
  at GameData.StartStandardModeGuide () [0x00000] in <filename unknown>:0 
  at GameLoader.FixedUpdate () [0x00000] in <filename unknown>:0 
```

One idea for remediation would be to force the creation of a suitable planet in star 0 if there otherwise isn't one.

Another idea would be to allow the `UniverseGen::CreateGalaxy` to search the entire galaxy for an eligible birth planet (and then remediate anything that happens to rely on the birth star being index 0 :fire:).

**Comment by Touhma** [comment]
Hey there , yep it's a know bug. I'll be able to fix it by next release. :) 

Thanks for the report

**Comment by Touhma** [comment]
PS : in the meantime you can use ChanceBeingHabitable=1 in the configs

**Comment by Touhma** [comment]
should be fixed now - reopen if needed
