### ISSUE TITLE
Missing key resource in starting planet

### ISSUE THREAD

**Issue by ThanhNMSE130286** [Touhma/DSP_Plugins#101]
Just try the mod, the starting planet was minuscules and it was lacking coal, thus make it impossible to research sail tech and leave to other planet. => make sure starting planet always have certain size and have key resource.

**Comment by innominata** [comment]
The starting planet is already clamped to 50 minimum, which in my testing of 20 seeds always had all the resources. This is the second time I've had a report of coal missing, so I'll change it to minimum size of 60 and try that.

**Comment by innominata** [comment]
Committed to 1.4, with configurable value

**Comment by ThanhNMSE130286** [comment]
Can't you hard code in 1 node of iron, copper, coal to always be present,
or is it all rand gen?

Vào 10:59, T.2, 19 Th4, 2021 innominata ***@***.***> đã viết:

**Comment by innominata** [comment]
Not with the current version of the mod, its all procedurally generated at the moment. That's on the roadmap, but a while away

**Comment by innominata** [comment]
Fixed in 1.4
