### ISSUE TITLE
Sorters cant paste correctly

### ISSUE THREAD

**Issue by Varrus85** [Touhma/DSP_Plugins#109]
Hello,

I cant find this bug here, so i write a ticket. 

When i try to copy and paste a facility with sorters on conveyorbelts with another belt next to it, the dorter wants to reach the next one. I attach a Screenshot.

Im using the curent version of DSP and the mod and tested it with only the mod.
![20210715084415_1](https://user-images.githubusercontent.com/87465885/125743237-8074a952-cb64-4665-b9be-784830857d59.jpg)

**Comment by innominata** [comment]
What size planet?

**Comment by Varrus85** [comment]
The Max size

**Comment by Varrus85** [comment]
I started a new game and now it works normaly, thank you for your fast help =D

**Comment by Varrus85** [comment]
The bug occurs at planet size 490 - 510

**Comment by innominata** [comment]
Very strange that it would only happen in cheatmode. The only difference is research is automatically unlocked.

**Comment by Varrus85** [comment]
Now im playing on max 400 and i have no problems so far, i get the bug in normal mode, in cheat mode it works. Btw i love your mod!! Very good work!! And sorry for my english im german ...

**Comment by innominata** [comment]
I've tried at 490 500 and 510, with cheatmode on and off, have not been able to reproduce.
Thanks :)

**Comment by innominata** [comment]
It might be related to having a huge amount of belts on a planet? did you have a lot of factory already built?

**Comment by Varrus85** [comment]
I tried it with the first 20 belt and a container you get from the basic logistic research

**Comment by Varrus85** [comment]
When i copy the container with the sorter it already makes the sorter one grid larger.
![20210717113810_1](https://user-images.githubusercontent.com/87465885/126032912-b536bf98-2646-4d24-8f5a-f43046abcfe2.jpg)

**Comment by innominata** [comment]
We've reproduced this, now we just have to figure out what's causing it :)

**Comment by Varrus85** [comment]
Yay!! Good luck!

**Comment by innominata** [comment]
In saying that, blueprint patch is out in 2 days, and will likely replace anything I do with errors. So it will have to wait til then sorry :)

**Comment by innominata** [comment]
Ok, still broken. Looking for cure

**Comment by innominata** [comment]
https://github.com/Touhma/DSP_Plugins/releases/tag/2.0.beta.75.2

**Comment by innominata** [comment]
Let me know if that doesnt fix it

**Comment by Varrus85** [comment]
Sorter bug is fixed for me. Thank you, great work.

**Comment by innominata** [comment]
Unfortunately it's not so simple, the other planet sizes have similar issues and I'm trying to track down the root cause which will probably have to be in a 2.1 patch as it will break saves. It's also related to blueprints from different size planets not being grid aligned. Not sure if its solvable, but I'm trying

**Comment by JamieRCHI** [comment]
I just started a new game with a Planet size of 510. When pasting with sorters, sometimes the sorter connects to the closer belt instead of the 2nd or 3rd Belt over. Maybe for now I should go back to the 400 size planet. Had no issues with that.

**Comment by innominata** [comment]
Unfortunately planets above around 450 end up straddling the line between having inserters end up too far or too close, when you have them in certain orientations at certain latitudes. The parameters it uses now minimize it as much as possible, but a proper fix would require rewriting the logic completely, something that is a bit beyond my abilities

**Comment by innominata** [comment]
A workaround could be to only orient inserters north-south

**Comment by JamieRCHI** [comment]
Thanks for looking at this. It doesn't happen often, and I don't think it ever happens when placing a blueprint, so I can live with it. 
I do usually orient my builds parallel to the equater so that helps.

**Comment by innominata** [comment]
Strangely blueprints seem to be unaffected, so you can also get around it by using them
