### ISSUE TITLE
Belts Invisible

### ISSUE THREAD

**Issue by enterthegungeonnoob** [Touhma/DSP_Plugins#11]
Any conveyor belts I place are invisible, restarted the game and that did not fix it, generated 251 stars at start with infinite resources.

**Comment by Touhma** [comment]
![image](https://user-images.githubusercontent.com/8696405/108518051-2537b200-7296-11eb-878f-32f0bb90b7da.png)
Seems working on my side ... are you sure it's not releated to an another mod ?

**Comment by Touhma** [comment]
![image](https://user-images.githubusercontent.com/8696405/108520226-7052c480-7298-11eb-888e-b24b2f847012.png)
Alright ... sometime on big planets the belt are sligtly under the ground

**Comment by Touhma** [comment]
![image](https://user-images.githubusercontent.com/8696405/108639630-8d87be80-7463-11eb-8dab-cf2729e94e04.png)
Fixed

**Comment by Touhma** [comment]
reopen the issue if you still have it
