### ISSUE TITLE
logistic vessels do not land at ILS

### ISSUE THREAD

**Issue by ab9rf** [Touhma/DSP_Plugins#114]
I've had this happen twice now: incoming logistic vessels do not land at the ILS; they instead hover about 50 meters above the station and never progress further.

![20210720235956_1](https://user-images.githubusercontent.com/1445859/126433559-dabe8873-d486-4012-a5d0-07a754b858f9.jpg)

This only happens in saves when I have Galactic Scale loaded.

**Comment by innominata** [comment]
Im assuming these are on planet 10 and up?
We had this problem before and fixed it, I'm thinking something in DSP has changed and the fix is no longer working

**Comment by ab9rf** [comment]
Yes, planet number 10, it was number 11 in the other save that did not work.

**Comment by innominata** [comment]
Oooh, thats also good to know. Trying to sort this one out now

**Comment by innominata** [comment]
I havent been able to reproduce, are you able to send a save?

**Comment by innominata** [comment]
As far as I can tell the code is still working

**Comment by ab9rf** [comment]
https://drive.google.com/file/d/1l7G2X28PX2lVrUUwkCG2Vr1wn4-xwOam/view?usp=sharing

**Comment by innominata** [comment]
I've found a fix for the trash flying into space, however it breaks saves

**Comment by innominata** [comment]
However it doesnt break your save. :)
In addition, drones are working perfect on your save, at least on the current dev build

**Comment by ab9rf** [comment]
I'm on the public release, so perhaps that might be the difference.

**Comment by innominata** [comment]
Looks like saves breaking was an unrelated bug. I'll try your save again with the same version you're on. Do you have discord?

**Comment by innominata** [comment]
[GalacticScale2b74.zip](https://github.com/Touhma/DSP_Plugins/files/6854270/GalacticScale2b74.zip)
Try this one

**Comment by innominata** [comment]
You wouldnt be using planetminer mod would you?

**Comment by ab9rf** [comment]
Yes, I am using PanetMiner.

**Comment by ab9rf** [comment]
Same behavior using the above dll. Disabling PlanetMiner also has no effect.

**Comment by innominata** [comment]
Station range limiter replaces the method which we patch to fix this issue :) I might do a pull request and see if they will fix it

**Comment by innominata** [comment]
[StationRangeLimiter.zip](https://github.com/Touhma/DSP_Plugins/files/6856400/StationRangeLimiter.zip)
I've patched their code, and built a copy for you, I've submitted the modification, hopefully they will include it in their mod.

**Comment by ab9rf** [comment]
That's terribly generous of you. Thanks for your attention to this issue.
