### ISSUE TITLE
Infinite height hills

### ISSUE THREAD

**Issue by enterthegungeonnoob** [Touhma/DSP_Plugins#12]
Upon reloading the game anywhere I had placed structures was suddenly consumed by hills of infinite height

**Comment by Touhma** [comment]
Can you send me a screen shot / seed ?

**Comment by Touhma** [comment]
![image](https://user-images.githubusercontent.com/8696405/108518388-7fd10e00-7296-11eb-8466-7534c529a1be.png)
Yep , definitely a bug

**Comment by Touhma** [comment]
In the meantime you can build anything around you and the ground will be leveled again ^^

**Comment by Touhma** [comment]
reopen the issue if you still have it
