### ISSUE TITLE
Some issues with GS2 and blueprints

### ISSUE THREAD

**Issue by VladParshin** [Touhma/DSP_Plugins#124]
Although I am not too sure this is not a vanilla issue, I believe it is related to planet sizes.

The issue is that, a lot of items that are stackable (such as containers) as well as items such as the Planetary/Interstellar ports, cannot be copied via the blueprint, as it 'exceeds in maximum height for vertical construction'.

I'm currently playing with a 500 (max) start planet scale for reference.

I will test it with a smaller size in a moment, but I just got to the point of making ports, and it's been a huge problem with copying layouts so far.

<just tested. Blueprints work fine on Vanilla preset>

**Comment by innominata** [comment]
It's a known issue I'm going to try and fix today, thanks

**Comment by innominata** [comment]
Fixed
