### ISSUE TITLE
Cant walk on home planet 

### ISSUE THREAD

**Issue by Cdeeks** [Touhma/DSP_Plugins#13]
As soon as you land on home starter planet you move your mech you get error and game breaks. tested with seed 
![image](https://user-images.githubusercontent.com/28351385/108519700-ce47d200-72c1-11eb-84f0-4f794c36a391.png)

![image](https://user-images.githubusercontent.com/28351385/108519755-dd2e8480-72c1-11eb-9e6d-e01cda21f47c.png)

**Comment by Touhma** [comment]
should be fixed now - reopen if needed
