### ISSUE TITLE
[GalacticScale 2.1.9] Some stars may have negative age

### ISSUE THREAD

**Issue by phoenixx-666** [Touhma/DSP_Plugins#137]
I've generated a cluster and it yielded a Red Giant named Oto with negative age. I attach the JSON of my generated cluster.
[My First Custom Galaxy.zip](https://github.com/Touhma/DSP_Plugins/files/7062420/My.First.Custom.Galaxy.zip)

**Comment by innominata** [comment]
Well that's weird.

**Comment by innominata** [comment]
Found the bug, an errant - :)
Fixed in 2.1.18
