### ISSUE TITLE
"Requires foundation support" on normal ground

### ISSUE THREAD

**Issue by ExoStatic145** [Touhma/DSP_Plugins#14]
Started new game with seed: 39601132

Cannot place any structures because the error "Requires foundation support" is present no matter where I try to place the building.

Included is screenshot and config file (as TXT because CFG not supported)

[touhma.dsp.galactic-scale.star-system-generation.txt](https://github.com/Touhma/DSP_Plugins/files/6011142/touhma.dsp.galactic-scale.star-system-generation.txt)

![Desktop Screenshot 2021 02 19 - 15 41 21 52](https://user-images.githubusercontent.com/58098080/108526815-7d3bdc00-72c9-11eb-806e-fdf0fc0f2fe3.png)

**Comment by Ixam97** [comment]
I have the exact same issue, using 1.0.8

**Comment by Touhma** [comment]
reopen the issue if you still have it
