### ISSUE TITLE
Unable to land transport ships

### ISSUE THREAD

**Issue by LordCorellon** [Touhma/DSP_Plugins#140]
Have a planet (only planet in my starter system with Titanium) where after launching a interplanetary transports they are unable to dock and land instead seem to get stuck "landing" about 20 grid lines to the side.  

Transports launched from the planet can land on my home planet fine, but upon return they too get stuck trying to "Land" 20 grid lines beside the interplanetary station.

I've tried relocating the station and that did not have any effect, new ships attempting to land get stuck as well

**Comment by RatherMiro** [comment]
Same issue here, cannot dock. The ships are shaking beside the station. But this is fine when the number of planets is default.There are almost 20 planets in my system.

**Comment by innominata** [comment]
This is a problem we have had and fixed before, looks like a DSP update has reintroduced it. I'll see what I can do to fix it. Is anyone able to provide a save game?

**Comment by innominata** [comment]
https://dsp.thunderstore.io/package/download/Galactic_Scale/GalacticScale/2.2.6/
Fixed
