### ISSUE TITLE
Unable to Launch 2.2.0.6

### ISSUE THREAD

**Issue by LordCorellon** [Touhma/DSP_Plugins#141]
2.2.0.5 Launches correctly (However has the transport bug) attempting to launch 2.2.0.6 results in a grey screen and no splash.

> Bepin loader logs stop after:
> [Message:   BepInEx] BepInEx 5.4.11.0 - DSPGAME
> [Info   :   BepInEx] Running under Unity v2018.4.12.5889476
> [Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
> [Info   :   BepInEx] Supports SRE: False
> [Info   :   BepInEx] System platform: Bits64, Windows
> [Message:   BepInEx] Preloader started
> [Info   :   BepInEx] 1 patcher plugin loaded
> [Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
> [Message:   BepInEx] Preloader finished
> [Message:   BepInEx] Chainloader ready
> [Message:   BepInEx] Chainloader started
> [Info   :   BepInEx] 3 plugins to load
> [Warning:   BepInEx] Plugin [NebulaMultiplayerModApi 1.1.0.4] targets a wrong version of BepInEx (5.4.15.0) and might not work until you update
> [Info   :   BepInEx] Loading [Galactic Scale 2 Plug-In 2.2.0.6]
> [Message:       GS2]  
> [Message:       GS2] .─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─_─.
> [Message:       GS2] │  ╔═╗┌─┐┬  ┌─┐┌─┐┌┬┐┬┌─┐  ╔═╗┌─┐┌─┐┬  ┌─┐                                │
> [Message:       GS2] │  ║ ╦├─┤│  ├─┤│   │ ││    ╚═╗│  ├─┤│  ├┤                                 │
> [Message:       GS2] │  ╚═╝┴ ┴┴─┘┴ ┴└─┘ ┴ ┴└─┘  ╚═╝└─┘┴ ┴┴─┘└─┘ Version 2.2.0.6 Initializing   │
> [Message:       GS2] └──────https://discord.gg/NbpBn6gM6d──────────────────────────────────────┘

Tried manually installing Bepin 5.4.16 with no change

**Comment by innominata** [comment]
[GalacticScale.zip](https://github.com/Touhma/DSP_Plugins/files/7261851/GalacticScale.zip)
Try this rebuild?

**Comment by innominata** [comment]
also try updating nebula api to 1.1.1
https://dsp.thunderstore.io/package/download/nebula/NebulaMultiplayerModApi/1.1.1/

**Comment by LordCorellon** [comment]
Somewhat better, Updating Nebula didn't do anything but the rebuild allows the game to  launch if I let it sit for long enough.

In 2.2.05 when I would launch the game it would goto a black screen for 2-5 seconds then the DSP logo would show and it would switch to the GSM splash screens with the loading bar before going to the main menu.  And when I quit the game it would goto the "Safe Exiting" screen for 5-10 seconds and then go back to the main menu (or desktop depending on the selected choice)

In 2.2.0.6 when I launch the game I don't get a DSP logo but a grey screen with the windows "Waiting" cursor and with the rebuild if I let it sit on that screen for 1 minute and 38 seconds it will then goto a black screen with the Dyson Sphere mouse icon and sit on that screen for another 32 s seconds before loading the GSM splash screen and loading the game.   When I exit the game it would goto the "Safe exiting" splash and sit there for longer then I have patience to find out... (At least 3 minutes before I just end up force quiting it)

This only occurs when 2.2.0.6 is loaded (With other mods or alone  (minus dependencies for GSM) and 2.2.0.5 doesn't act that way.    

The following two lines are the next in the log after the splash starts to show:
> [Info   :   BepInEx] Loading [NebulaMultiplayerModApi 1.1.1.6]
> [Info   :   BepInEx] Loading [Galactic Scale 2 Nebula Compatibility Plug-In 1.0.0.0]
> [Message:GS2DepCheck] Loaded

So it would appear to be taking place between GSM and before Nebula, I'm not sure of the mod structure but is there any initialization routines that could be looping or recusing?
>

**Comment by innominata** [comment]
Try deleting the nebula api dll and see if that fixes it?
GS2 should be able to run fine without it

**Comment by innominata** [comment]
if you have discord, easier to sort it out there

https://discord.gg/JNFKjzGhMK

**Comment by LordCorellon** [comment]
Same thing with Nebula deleted, I've responded to your comment in discord in general but if another channel or PM is better let me know username in discord is Corello

**Comment by LordCorellon** [comment]
Fixed in 2.2.0.7
