### ISSUE TITLE
Placing EM Rail Ejector Error

### ISSUE THREAD

**Issue by andrewluebke** [Touhma/DSP_Plugins#144]
I'm getting the following error when I try to place an EM Rail Ejector:

Error Type: Star Parameter Mod
Game Time: 23:05:10
Detail Log: sub type: 1, star id: 31, star type: 1, star mass: 51936, star lum: 32829, threshold lum: 27

I've tried it on all planets in the system with the same error.

**Comment by innominata** [comment]
Where is the error shown?

**Comment by andrewluebke** [comment]
Seems to have gone away.  Can't duplicate it.
