### ISSUE TITLE
Starting planet star type not respected above about 375 stars

### ISSUE THREAD

**Issue by andrewluebke** [Touhma/DSP_Plugins#148]
If I tell GS2 to use a Blue Giant star for the starting system it does up to about 372 stars.  At 375 stars I see another type.  An example is for seed 3556071.  Actually it doesn't appear to be repeatable.  I've tried with the same seed and I can't go above 129.

<img width="1920" alt="2022-01-15 10_29_14-Greenshot" src="https://user-images.githubusercontent.com/45699172/149633562-12d817e8-8842-41da-a02a-511d2c8e66a5.png">

<img width="1920" alt="2022-01-15 10_29_43-Greenshot" src="https://user-images.githubusercontent.com/45699172/149633573-9c71deb4-500f-4957-a26f-d7eda18960b8.png">

**Comment by innominata** [comment]
Interesting, I'll take a look thanks

**Comment by andrewluebke** [comment]
A couple of observations...  If I start a new modded game with 1024 as the default number of stars it starts with the selected star type (blue giant in my case).  If I change the number of stars it sometimes stays blue giant but usually changes.  Once it's started not being the default selection it will always be something else when I start a new game until I restart the game which seems to switch it back to working once.  Anyway it seems very nondeterministic.

**Comment by innominata** [comment]
Can you try it again with 2.2.0.23? I've reverted the galaxy generation code back a half dozen versions, might solve this. 
If you can join our discord https://discord.gg/Cywc7SVuxJ might be easier to remind me to fix this :) I keep forgetting to look at github
