### ISSUE TITLE
Galactic Scale

### ISSUE THREAD

**Issue by LiberV1r** [Touhma/DSP_Plugins#149]
Found an interesting issue - apparently moons can spawn too close to a gas giant to land on them.  The game loads the transition to the gas giant instead of the moon you're trying to get to, making it impossible to land on the moon.

![image](https://user-images.githubusercontent.com/41840348/149637398-7fc77a65-dee3-4466-9ac5-d5b2863a58e7.png)

**Comment by LiberV1r** [comment]
Here's a copy of the save.
[wierdness.zip](https://github.com/Touhma/DSP_Plugins/files/7875878/wierdness.zip)

**Comment by LiberV1r** [comment]
list ' o mods

![image](https://user-images.githubusercontent.com/41840348/149637671-6898b75d-ea30-4816-ba10-14ea15982d01.png)

**Comment by innominata** [comment]
Thanks for that I'm hoping to get some time to sort this today

**Comment by innominata** [comment]
Fixed in 2.2.0.18
