### ISSUE TITLE
[Idea] Planet generation configuration

### ISSUE THREAD

**Issue by Apothicon02** [Touhma/DSP_Plugins#15]
Additional configuration in the mod to altar the planets themselves would be a very interesting feature to add to the mod.

For example, some configuration options could be:
- Changing the height of hills per planet type
- Changing which materials the ground is made of per planet type
- Changing the amount of buildable area per planet type (ex. smaller oceans on mediterranean planets or bigger lava crevices on lava planets)
- Changing the density of foliage such as trees per planet type
- Maybe changing which foilage spawns on certain planet types

**Comment by Touhma** [comment]
Changing the height of hills per planet type --> possible and I know how to do it but i'm not supporting it YET  --> Planet update No ETA
Changing which materials the ground is made of per planet type --> will come in the future with a biome update, no ETA 
Changing the amount of buildable area per planet type --> should be possible 
Changing the density of foliage such as trees per planet type --> possible in some limits for now ( hardcoded values in the game engine ) --> Planet update
Maybe changing which foilage spawns on certain planet types ---> Biome update

**Comment by MeiVinEight** [comment]
Generator's naming algorithm
Is it possible to use the native star naming algorithm?

**Comment by innominata** [comment]
> Generator's naming algorithm
> Is it possible to use the native star naming algorithm?

That's a bug and will be sorted in next patch

**Comment by innominata** [comment]
> Additional configuration in the mod to altar the planets themselves would be a very interesting feature to add to the mod.
> 
> For example, some configuration options could be:
> 
> * Changing the height of hills per planet type
> * Changing which materials the ground is made of per planet type
> * Changing the amount of buildable area per planet type (ex. smaller oceans on mediterranean planets or bigger lava crevices on lava planets)
> * Changing the density of foliage such as trees per planet type
> * Maybe changing which foilage spawns on certain planet types

All added in 2.0

**Comment by innominata** [comment]
2.0 Released
