### ISSUE TITLE
GS2_Cheats error

### ISSUE THREAD

**Issue by LiberV1r** [Touhma/DSP_Plugins#152]
![image](https://user-images.githubusercontent.com/41840348/150617512-d9f08252-3727-4498-b147-cdb1b14941f2.png)

GS2_cheats causes the attached error since the update.

**Comment by Chase-san** [comment]
This prevents building buildings. I just disabled the cheats mod and everything seems to work.

**Comment by innominata** [comment]
I've updated GS2Cheats.
