### ISSUE TITLE
Moon can not be landed if its orbit too close to a gas giant

### ISSUE THREAD

**Issue by DBucket29** [Touhma/DSP_Plugins#153]
![屏幕截图 2022-01-22 132106](https://user-images.githubusercontent.com/98202894/150626208-f2210158-0f40-46da-ad16-df0753f53392.png)
![屏幕截图 2022-01-22 132148](https://user-images.githubusercontent.com/98202894/150626213-0170ff11-28d5-4e3f-8668-5f4ad29b4761.png)

**Comment by innominata** [comment]
https://dsp.thunderstore.io/package/download/Galactic_Scale/GalacticScale/2.2.22/

**Comment by DBucket29** [comment]
> https://dsp.thunderstore.io/package/download/Galactic_Scale/GalacticScale/2.2.22/

Thanks
