### ISSUE TITLE
Buttons not working+ a wonky/fynky as system

### ISSUE THREAD

**Issue by SGZ-Creations** [Touhma/DSP_Plugins#155]
Have no idea on how u think i'm suppose to enable this imaged setting of yours ?
![image](https://user-images.githubusercontent.com/59801736/151169374-a8689971-aadb-40cb-abd9-37816b33e893.png)

Also would there be a way to dissable mentioned setting afterwards or could u implement a non cheating way of adding ore patches. So i can fix my system to have more copper than image shows. since i think i'm unable to reach the gravity matrix before runing out of copper. :)
![image](https://user-images.githubusercontent.com/59801736/151169886-da7ba155-6c8d-438b-9517-61888bee7097.png)

**Comment by innominata** [comment]
Should be no problem getting warpers with that much copper?
I'd suggest using debug/teleport to check out a system before committing to playing it. When you find something that looks good, save, then tp around and make sure its going to work. then disable tp, reload your save and play

**Comment by innominata** [comment]
(As for the button, I'll have to check on that, DSP changed the way infinite ores are handled and it might not work any more)
