### ISSUE TITLE
Geothermal power stations not working

### ISSUE THREAD

**Issue by Taybal** [Touhma/DSP_Plugins#156]
The Geothermal power stations recently added in DSP major update patch does not seem to work on lava. Always outputs 0% power. Maybe planets are missing some data for geothermal output to work properly.

**Comment by innominata** [comment]
[GalacticScale_Geothermal_Test.zip](https://github.com/Touhma/DSP_Plugins/files/7946253/GalacticScale_Geothermal_Test.zip)
Try this

**Comment by Taybal** [comment]
Does not seem to fix anything, I tried on an already generated galaxy and on a newly generated one on molten lava worlds after manually replacing the plugin .dll file with the one you provided in the plugin's installation folder under thunderstorm mod manager profile's folder

**Comment by innominata** [comment]
Are you able to send a save showing the problem?

**Comment by innominata** [comment]
[GalacticScale Geothermal Test 2.zip](https://github.com/Touhma/DSP_Plugins/files/7954076/GalacticScale.Geothermal.Test.2.zip)

**Comment by innominata** [comment]
https://github.com/Touhma/DSP_Plugins/releases/download/2.2.0.24/Galactic_Scale-GalacticScale.zip
