### ISSUE TITLE
NullReferenceException when loading planet (GS 2.2.0.23)

### ISSUE THREAD

**Issue by nclow** [Touhma/DSP_Plugins#157]
Using a savegame that had been generated with an earlier version of GS with some custom generation settings.

Updated mod from 2.2.0.22 to 2.2.0.23.
Warped to a new system and landed on a planet, and got this stack trace.

![GS3](https://user-images.githubusercontent.com/4174570/151296558-ed9f5b39-5e0c-4f15-a53d-d047874a0cf9.png)

Exiting and reloading the game fixed it. The planet loaded with no issues.

Traveled to a new system (never visited) and landed on a new planet. Same error. Reloading fixed it and the new planet loaded with no problems.

I then traveled back to my primary system and landed on my main planet and it loaded with no error.

**Comment by innominata** [comment]
Thanks I'll look into it

**Comment by innominata** [comment]
Are you using other mods? Nobody else is having any issues like this

**Comment by nclow** [comment]
I'm using other mods. With my set of mods, I was able to reproduce the problem very consistently, so I started trimming to see which mod might be responsible. I disabled several mods until I couldn't disable any more.

My save file will load with this set of mods.

BepinEx 5.4.17
LDBTool 2.0.5
NebulaMultiplayerModApi 1.1.2
DSPModSave 1.1.3
CommonAPI 1.4.0
PersonalLogistics 2.7.1
AutoStationConfig 1.3.2
GalacticScale 2.2.0.23
RebindBuilBar 1.0.2
BetterMachines 1.0.5
GigaStationsUpdated 2.2.7

My test was to fly out to a system I'd never been to before and land on a new planet. With the above mod list, I didn't encounter an error doing this. But when I added DSPAllPlanetInfo 1.1.3 to the above list and tried my test again, I got the same stack trace as reported when landing on the new planet.

**Comment by nclow** [comment]
The same problem occurs when using DSPAllPlanetInfo 1.1.3 with GS 2.2.0.24

**Comment by nclow** [comment]
I think 1.1.4 of DSPAllPlanetInfo has resolved this. It probably had nothing to do with GS. Thank you. I'll close this issue.

**Comment by innominata** [comment]
I'm not sure if you're on our discord, but its the best place to get help :) I only check my emails when I'm at work so weekends are a dead zone for me on here unless I chance by
