### ISSUE TITLE
Empty space on blueprints

### ISSUE THREAD

**Issue by sdeligar** [Touhma/DSP_Plugins#159]
I recently started using your mod and noticed that after installation all of my blueprints have large empty spaces added onto the ends of them that make it difficult to place. I've attached a screenshot showing what I mean.
![DSPGalacticScalebug](https://user-images.githubusercontent.com/100451659/155821320-9ea0a584-4133-4a3d-99dc-d64b86674eef.png)

**Comment by innominata** [comment]
Not sure why this is happening, but isn't the only blueprint related bug. I would suggest blueprinttweaks mod and shift placing to get around it

**Comment by sdeligar** [comment]
Actually, this is the same bug you fixed with GS Experimental update 2.3.12 I just forgot to close it here. Sorry!

**Comment by innominata** [comment]
thats super weird :P all I did was remove debug logging!

**Comment by ratsputin** [comment]
I'm seeing the same issue both on an existing game opened after adding this mod and a new game started with this mod.

This is with 2.4.4.
