### ISSUE TITLE
[Bug] Corrupted Savefile on New Game with unlimited Ressources at ~100 systems

### ISSUE THREAD

**Issue by Luciferonlinux** [Touhma/DSP_Plugins#16]
So I wanted to Start a new Game with around 300 stars and also for Testing purposes with unlimited Ressources, but I got this Errormessage and the game didn't even load into the prolouge:
![DSP_Galacticscale_Corrupted](https://user-images.githubusercontent.com/50619620/108561469-9dd25900-72fe-11eb-9815-1ccaf8fc37b6.PNG)
After testing a few times with a lower amount of stars, and it seems to be at around 100 stars that the message started appearing. I'm using Windows 10, installed it trough Steam and using the r2modman modmanager the Version 1.0.8. of the mod.
I have no idea if the game logs Crashes, if it does, i will upload one.

**Comment by Touhma** [comment]
Hummmm weird ... Are you sur you don't have multiples version of the mod installed ? ( check your plugin folder )

**Comment by blacksythe** [comment]
Can replicate this with just your plugin and BEP loaded, same conditions, however managed to get it to load several times with 250 stars ok. 250-350 was sometimes ok (may be system differences who knows) However 350+ was a dead cert of this error occuring.

Would like to note with several other plugins loaded this limit is much lower.

**Comment by Touhma** [comment]
should be fixed now - reopen if needed
