### ISSUE TITLE
Extra space highlighted around selected area when making blueprint

### ISSUE THREAD

**Issue by ratsputin** [Touhma/DSP_Plugins#162]
![20220305122211_1](https://user-images.githubusercontent.com/32401888/156895655-e01d8dea-7943-4f4d-b6f1-982755939e9d.jpg)

Version: GalacticScale v2.4.4
DSP version: 0.9.24.11286
r2modman version: 3.1.27

I was able to reproduce this on a fresh install on a new machine.  Steps I followed:

- Install Steam and DSP
- Install r2modman
- Install mods: BlueprintTweaks, GalacticScale, SplitterOverBelt, CruiseAssist, BetterStats (disabling mods makes no difference)

Start new game with default settings but use GS2 generator and unlimited resources

Play through until able to do blueprints.  Place a building and copy just it.  Result is shown in screenshot.

Both machines (the machine I originally encountered this on and the one I just reproduced it on) are running Windows 11.  This one is a laptop with an Nvidia GeForce RTX 2070 super with an Intel Core-i7.  The other machine I originally found the issue on is a desktop with an AMD Ryzen 9 3950X and an Nvidia RTX 2080Ti.

Disabling various mods has no effect on behavior.  I haven't tested disabling Galactic Scale mod (since the savegame won't work); however, on my other machine, I didn't encounter this issue until I enabled Galactic Scale mod.

**Comment by ratsputin** [comment]
I just noticed that having GalacticScale enabled seems to break BlueprintTweaks.  At least v1.4.6.  With GalacticScale running, I can't access any of the features of BlueprintTweaks.

**Comment by innominata** [comment]
Will look into it, thanks

**Comment by innominata** [comment]
Fixed in 2.4.9 :)

**Comment by innominata** [comment]
https://dsp.thunderstore.io/package/Galactic_Scale/GalacticScale/

**Comment by ratsputin** [comment]
Works like a champ!  Thank you so much for fixing this and developing such a great mod!

**Comment by innominata** [comment]
Thanks for discovering the bug and playing :D
