### ISSUE TITLE
Short save names (shorter than lastexit or autosave) cause an error on manual save

### ISSUE THREAD

**Issue by marr75** [Touhma/DSP_Plugins#164]
Currently, any save file with a name shorter than 8 characters will throw an error on manual save. The error can be found at Line 17 of the SaveCurrentGame.cs source file. The `String.StartsWith` method is probably a safer way to achieve this functionality.

**Comment by ChoadScholar** [comment]
Seeing the same thing here:
![image](https://user-images.githubusercontent.com/78493141/157225520-e7f329d8-a45f-48f8-9017-af378f272f22.png)

**Comment by innominata** [comment]
Yeah sorry, should be fixed in 2.4.7, caught this myself last night
https://dsp.thunderstore.io/package/Galactic_Scale/GalacticScale/
