### ISSUE TITLE
blueprint

### ISSUE THREAD

**Issue by Danielio001** [Touhma/DSP_Plugins#165]
after 2.4.9 upon selecting a blue print it opens with nothing and a red error in the corner
![Untitled](https://user-images.githubusercontent.com/101408562/157881618-4c546655-b68e-46ab-b13f-562f17033f04.png)
![Untitdled](https://user-images.githubusercontent.com/101408562/157881635-fa8c250b-4056-4cc8-b316-9a326b7fb0d4.png)

**Comment by innominata** [comment]
That's definitely not ideal, I'll look into it

**Comment by innominata** [comment]
should be fixed in 2.4.12
https://dsp.thunderstore.io/package/download/Galactic_Scale/GalacticScale/2.4.12/

**Comment by NanoZeal** [comment]
![20220312193737_1](https://user-images.githubusercontent.com/99779582/158042655-87bb9686-8973-41b8-b7a6-8aba564dbd5a.jpg)
Got this error 3 times in a row, each time after copying in blueprint mode. I can still copy and paste things, but just in case I figured i'd share here as this only happened after 2.4.12. Let me know if you need anything else.
P.S. thank you all for everything you have done and continue to do for this wonderful mod. Cheers!

**Comment by innominata** [comment]
What size planet? is it only with long blueprints like that?

**Comment by innominata** [comment]
[GalacticScale.zip](https://github.com/Touhma/DSP_Plugins/files/8240407/GalacticScale.zip)
Can you try replacing the GalacticScale.dll in 
C:\Users\{Username}\AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\profiles\Default\BepInEx\plugins\Galactic_Scale_GalacticScale
Or where you installed GS if you're not using modman

**Comment by NanoZeal** [comment]
The planet size is a 200 default size. Also tried different copy and paste methods, and it does seem to only throw the error when it is a long blueprint like that.
I extracted the zip and replaced the old GalacticScale.dll with the new one. Want me to test if it still causes an error?

**Comment by NanoZeal** [comment]
That seemed to work. No error at all when copying and pasting the blueprint

**Comment by innominata** [comment]
Excellent, I'll release it :)

**Comment by Danielio001** [comment]
works now
thank you very much
