### ISSUE TITLE
[GalacticScale] [Bug] Gas giants not showing up

### ISSUE THREAD

**Issue by natsuru95** [Touhma/DSP_Plugins#17]
just running your scale mod 1.0.8 atm i tried some seeds and some of the gas giants that should be there via star map info are just not visible
![grafik](https://user-images.githubusercontent.com/79341770/108574014-712a3b80-7316-11eb-96a1-ba835745b303.png)
![grafik](https://user-images.githubusercontent.com/79341770/108574041-843d0b80-7316-11eb-8d20-8ba4b34c3da5.png)

**Comment by Touhma** [comment]
Well technically you are walking on a gas giant so that should not happen xD
will be fixed when I fix the starting point ;)

**Comment by Sherkhan-1** [comment]
I have not seen this bug per-say, but I started a game and had a moon around the starting planet. However when I got to the point to go there - the game thought the moon was a gas giant - had mineral fields, etc all over - but I could not build anything.
Wondering if they are somehow related?

**Comment by Touhma** [comment]
should be fixed now - reopen if needed
