### ISSUE TITLE
System.NullReferenceException at GalacticScale.PatchOnWhatever.UpdateCursorView

### ISSUE THREAD

**Issue by kekegav2** [Touhma/DSP_Plugins#170]
Hi,
when I try to make a new GS2 game using vanilla GS2 generation I get the following error as soon as I open the starmap.
Mods from r2modman:
Bepinex
LDBtool
RailgunsRetargeting
NebulaMultiplayerModApi
GS2
BetterStats
CommonAPI
DSPModSave
CloseError

![20220319163605_1](https://user-images.githubusercontent.com/80983914/159128081-20e7f61c-2a0f-4a95-95d5-4c395163386b.jpg)
Is this a GS2 bug or caused by something else? Thanks for help.

**Comment by innominata** [comment]
Sounds like a bug with GS2, will look into it. You might be the first person to try Vanilla generation in a while :)

**Comment by innominata** [comment]
Fixed the bug but I need to test before releasing. Should be up ~5 hrs from now after I get home from work

**Comment by kekegav2** [comment]
The error is now gone. Thank you!

**Comment by innominata** [comment]
No problem! :D

For future reference, if you can join our discord I have notifications enabled, and github emails go to my work email address which I don't check over the weekend, so discord is a much quicker way to get in touch :)
