### ISSUE TITLE
Outdated Overridden Functions

### ISSUE THREAD

**Issue by dpmm99** [Touhma/DSP_Plugins#171]
All the differences I found that didn't seem obviously deliberate:
The "vegetables" code near the bottom of FlattenTerrain has changed a bit in the game (basically just looks like added SFX). The rest of that method looks up-to-date.
UISpaceGuide._OnLateUpdate has a sizable chunk missing at the bottom and I think a few other differences that weren't commented on in the code.
Ice 氷 has its own waterTypeId (-2) in OnPlanetDataSet but doesn't in the GalacticScale code.
There's a call to planetData.GenBirthPoints in the base game that isn't in GalacticScale's Modeler.Compute; maybe that one's intentional.
GameHistoryData.SetForNewGame is missing the "this.propertyData.Clear();" at the end.

I thought maybe this sort of thing is why I experienced some odd behaviors with GalacticScale like floating over ice instead of being able to walk and build on it, sorters sometimes not noticing belts or even being able to build on top of other objects on some smaller planets, planets being missing from the starmap until I get very close, and the planet generation causing noticeably more lag, but I guess not. I couldn't say any particular issue I came across was caused by GalacticScale since I have ~20 mods installed, so I just thought I'd take a look and not post separate issues for every possible thing that may actually not be related to GalacticScale.

Edit: the theme for Scarlet Ice Lake has different settings than the base game for music (since they just released some new tracks) and rare resources. I didn't check the other themes.

**Comment by innominata** [comment]
Hey there.
Vegetables code at the bottom of FlattenTerrain I'll look at.
UISpaceGuide._OnLateUpdate I'll look at.
Ice <- The themes have this, are you saying there's other places it's used that I'm overriding? Will look at
GenBirthPoints is dont in the GS2 VeinAlgorithm, I'll make sure its not missing, but birthpoints are being made, so its probably intentional.
this.propertyData is new in the latest update so I'll make sure.

Looks like I need to go through and diff the DSP versions, thanks for the tips!

**Comment by dpmm99** [comment]
Yes, sorry, I meant I was comparing OnPlanetDataSet in the GalacticScale code to the same function in the base game; that's the place where the waterTypeId differs.

You're welcome! Thanks for the mod! ;)

**Comment by innominata** [comment]
be good if you could join us on discord https://discord.gg/MQqdj2HMH7
you seem to have a bit of insight :)
