### ISSUE TITLE
fail to reopen saved game

### ISSUE THREAD

**Issue by ianbd** [Touhma/DSP_Plugins#172]
(DSP 0.9.25.12007) and GS2 2.5.3
The plugin works fine and saves the game. However whenever that save game is reopened that uses the GS2 mod DSP reports the save game data is corrupt and the galaxy cannot be recreated. The game then reports failing because no planets have been found and goes into an infinite start-up loop (splash screen and DSP rotating loading graphics).

I also get messages about log files that I was hoping to send but the path does not seem to be anywhere I can find the the DSP/user [DSP] structure.

**Comment by innominata** [comment]
Hi there, are you using the vanilla generator?
Try 2.5.5 and see if it loads? If that doesn't work are you able to join our discord where it will be easier to troubleshoot?
https://discord.gg/cpbNv5b392
