### ISSUE TITLE
Orbital Collector requires foundation support

### ISSUE THREAD

**Issue by Cringely** [Touhma/DSP_Plugins#173]
I've started a playthrough using the GS generator and have come to find I'm unable to place any orbital collectors.

This is on a "Gas Giant V" type planet. I have not yet tried any other Gas giants in the seed.
![image](https://user-images.githubusercontent.com/759077/165873762-9696cbe3-4825-41f6-8791-3421c1724093.png)

**Comment by innominata** [comment]
Are you using any other mods, specifically planet miner or anything else that changes mining?

**Comment by Cringely** [comment]
Not Planet Miner specifically, but yes. Thanks for asking, I just found an issue report on their repo reporting the same issue:
https://github.com/GoToNightmare/DSP-PlanetwideMining/issues/8

Thanks!

**Comment by innominata** [comment]
I'll build an updated version when I get home from work

**Comment by innominata** [comment]
[
[PlanetWideMining GS2 Fix 0.9.25 Source.zip](https://github.com/Touhma/DSP_Plugins/files/8601655/PlanetWideMining.GS2.Fix.0.9.25.Source.zip)
PlanetwideMining.zip](https://github.com/Touhma/DSP_Plugins/files/8601649/PlanetwideMining.zip)
