### ISSUE TITLE
Kimberlite Veins (and Fractal Silicon) Disappearing

### ISSUE THREAD

**Issue by kristopherlewandowski** [Touhma/DSP_Plugins#174]
I pull up the cluster map (ctrl+v) and find a system nearby with Kimberlite Veins listed. Fly to the system and click on each of the planets and none of them have Kimberlite Listed as veins on them. Zoom back out to galaxy map and the system I just flew to no longer has Kimberlite veins listed on it. I could replicate it on almost every system I flew to. Did this to probably 10 different stars.

From Galactic Map
![20220501104725_1](https://user-images.githubusercontent.com/63469553/166158117-3441368f-585d-4325-af1c-0f6346fe3f2f.jpg)

After flying to the system to see which planet has the vein and clicking each one, Kimberlite no longer listed:
![20220501104934_1](https://user-images.githubusercontent.com/63469553/166158150-ef394b71-e205-4536-9091-7c8616d47c9e.jpg)

Normally Ice Field Gelisols have Kimberlite in them from what I understand:
![20220501104946_1](https://user-images.githubusercontent.com/63469553/166158173-386fd20a-24fb-4ca1-a551-8a0fd15036ba.jpg)

**Comment by kristopherlewandowski** [comment]
I just noticed from my screenshots the Fractal Silicon Vein also disappeared from the list.

**Comment by innominata** [comment]
Do you have very small planets enabled by any chance?

**Comment by kristopherlewandowski** [comment]
I don't think so. I've uploaded the galaxy export. For the most part it was vanilla I didn't really modify too much. 
[My First Galaxy.zip](https://github.com/Touhma/DSP_Plugins/files/8599697/My.First.Galaxy.zip)

**Comment by kristopherlewandowski** [comment]
So playing around with this, it's also happening to Spiniform Stalagmites as well. Not sure what those 3 have in common besides all being rares. I've had no issues with it regarding Crude Oil, Organic Crystals, Optical Grating, Unipolar, or Fire Ice veins on the planets at least that I was able to recognize.

**Comment by innominata** [comment]
They are just rare, and subject to RNG. If you want to make sure they spawn there's an option in settings to force rares.
I'll think about how I can run the vein distribution algorithm before the planet is modelled, at least the part which determines whether the rares will spawn. Won't be perfect as veins wont spawn if there's no space, but should be better

**Comment by kristopherlewandowski** [comment]
Forcing rares appears to allow rares that shouldn't spawn on a planet around a certain star type to spawn and sometimes in mass quantities. One extreme to the other on that :) It is convenient to have all 8 mineable rares on one planet though.

Either way, just wanted to report it as it wasn't following the expected behavior experienced in the vanilla game.

Fantastic mod, I've really enjoyed punishing my rig with a huge star cluster.

**Comment by innominata** [comment]
yeah, vanilla gets around it by having a fixed planet size and fixed rare count. I had to rewrite all the vein placement code for GS to allow it to function with custom planets. I'll see if I can get it to report a bit better

**Comment by innominata** [comment]
Hopefully the latest update works a bit better
