### ISSUE TITLE
Is it possible to increase the maximum planet radius to over 510?

### ISSUE THREAD

**Issue by LittleSaya** [Touhma/DSP_Plugins#177]
I'm not sure if this kind of question is suitable here...if not suitable please remove or close this issue

I'm new to DSP modding, and have tried creating a planet with 600 radius, everything looks fine except the building grid is getting weirder as it's closer to the equater, or more accurately, from 24 degree north latitude to 24 degree south latitude.

Then I read some codes of GalacticScale and found the texture `_SegmentTable`, it's `512x4`, looks like that's why GS limited the planet radius to 510. I tried resizing the texture to `1024x4` and manually adjusted the LUT table to fit the size of the planet, but it finally turned out to be useless, everything looked just like the texture was `512x4`.

This is my code resizing the texture:

```c#
[HarmonyPrefix, HarmonyPatch(typeof(UIBuildingGrid), "Update")]
static bool Update (UIBuildingGrid __instance, Material ___material, ref Material ___blueprintMaterial, Material ___altMaterial)
{
    if (!DSPGame.IsMenuDemo && refreshFlag && ___material != null)
    {
        int segments = (int)(gridRadius / 4f + 0.1f) * 4;

        ___blueprintMaterial.SetFloat("_Segment", segments);

        newTexture = (Texture2D)___material.GetTexture("_SegmentTable");
        newTexture.Resize(1024, 4);
        for (int i = 0; i < 1024; ++i)
        {
            Color color = new Color(newLut[i] / 255f, newLut[i] / 255f, newLut[i] / 255f, 1f);
            newTexture.SetPixel(i, 0, color);
            newTexture.SetPixel(i, 1, color);
            newTexture.SetPixel(i, 2, color);
            newTexture.SetPixel(i, 3, color);
        }
        newTexture.Apply();

        refreshFlag = false;
    }
    return true;
}
```

It seems that when the texture's width is 512, every 1 step in X-axis of the texture equals to 1 latitude circle radius,
when the texture's width is 1024, every 1 step in X-axis of the texture equals to 1/2 latitude circle radius,
and that just limited the maximum to 512......

I thought there is something in the shader `VF Shaders/Gizmos/Building Grid` which takes some effects or does some extra calculations, so I managed to extract the shader and decompiled it, but I know nothing about shader, not to mention that the code I got was DXBC, some assembly codes. I used some tools to parse it, but still got nothing from it. (if you are interested I can upload the decompiled shader codes)

So, back to the title, is it possible to increase the upper limit of planet radius?

Or a completely different approach is needed to overcome those difficulties about building grid?

Now I'm installing intel GPA hoping to find something from the frame analysis (probably find nothing as I know nothing XD, maybe I should buy some books about shader first)

**Comment by innominata** [comment]
I had up to around 650 working on https://github.com/Touhma/DSP_Plugins/tree/SuperPlanets
But I gave up at that point, and switched back to 510.
I can't remember if the grid was working or not, thats possibly why I stopped. 
Anything higher than 650 hard crashed.

**Comment by LittleSaya** [comment]
> I had up to around 650 working on https://github.com/Touhma/DSP_Plugins/tree/SuperPlanets But I gave up at that point, and switched back to 510. I can't remember if the grid was working or not, thats possibly why I stopped. Anything higher than 650 hard crashed.

Thank you for replying, looks like you have tried resizing the texture to 1024x4, maybe I should try to find a way to replace the vanilla building grid.

And yes, the `heightData` in `PlanetRawData` is an unsigned short array, which I think limits the planet radius to about 655.

**Comment by innominata** [comment]
I'm pretty sure we replaced that with an int, but I cant find it quickly looking at the code, Hmm.
Might have been another short

**Comment by LittleSaya** [comment]
> I'm pretty sure we replaced that with an int, but I cant find it quickly looking at the code, Hmm. Might have been another short

You mean replacing `GetModPlane` with `GetModPlaneInt`? That's one of the short integers, I found another one:

<img width="325" alt="Annotation 2022-05-26 131604" src="https://user-images.githubusercontent.com/16049823/170421365-aadcf06c-11fa-49b7-9ca2-21b85ee2dbee.png">
<img width="477" alt="Annotation 2022-05-26 131621" src="https://user-images.githubusercontent.com/16049823/170421370-08743cc6-14e4-46de-b56e-8c295655a2b3.png">

It's an instance field, may be much harder to replace it with an int[].

It seems that buildings can still be put normally on planets larger than 510, they can snap to points on some kind of grid which is different from the building grid, looks like the building grid is just a visual effect.

**Comment by innominata** [comment]
That will be it.
Yeah the grid is purely visual. and very annoying. The blueprint grid is different again

**Comment by LittleSaya** [comment]
I closed this issue, looks like it will cost a lot of time and effort if we want to fix those problems brought by big radius...

Again, thank you for your replying, and thank your for creating GalacticScale, this is a wonderful mod, and your codes really helped me a lot when I'm trying to write my own mods ;-)

**Comment by Shad0wlife** [comment]
Just to comment: I tried 1024 as width, but the correlation to the grid ring was not clear. I believe it was neither stretched to every 2nd, nor was it extended and using the previous pixels.
We left it at that and decided to stick with 511 (so 510 because eounding to 10s at that size) there.
