### ISSUE TITLE
Error I don't understand

### ISSUE THREAD

**Issue by Fr3nch515** [Touhma/DSP_Plugins#178]
Hey yall, first of all thanks for all the modding. It's vastly improved the game. I'm receiving an error with the GalacticScale mod that I don't understand and need help deciphering. Not sure how to describe it other than it's just usual red box with a bunch of death letters. Screenshot attached. The new update may have something to do with it. I've lost a bunch of save games.

![Screenshot (116)](https://user-images.githubusercontent.com/107275311/173130342-d9cf6e4f-f7bb-4ddd-95cf-cf3a33c32c68.png)

**Comment by kenrya2** [comment]
Same here. The new update today (10th) seems to have broken something. I can't even get past the loading screen.

**Comment by innominata** [comment]
Sorry, forgot to check Github, their emails go to my work email and I don't check that on the weekend.
I released 2.5.14 and 2.5.15 which fixed it within a few hours. Hope you guys noticed and haven't been sitting waiting :)

https://dsp.thunderstore.io/package/Galactic_Scale/GalacticScale/
