### ISSUE TITLE
Most recent Galactic Scale forces saves into Sandbox Mode

### ISSUE THREAD

**Issue by Umbrasong** [Touhma/DSP_Plugins#179]
I updated to what my mod manager tells me is 2.7.1 (with the BACKUP SAVES) warning.  I started a new game to avoid any potential issues with previous saves.  All seemed well...until I saved and went to load the save.

I had started the game with "sandbox mode" UNchecked -- however, on loading the save, I was now in sandbox mode.

Testing with the mod disabled shows saves NOT toggling the state of sandbox mode on save/load.

**Comment by innominata** [comment]
I'm not sure if it's because of GS2's patching of the load screen, but there's a checkbox at the bottom that starts checked that you need to uncheck.
It could be defaulting checked just because its modded, I need to investigate more

**Comment by kittle31** [comment]
The issue is even more fun when you use the 'continue' option.  It starts your game in sandbox mode like it or else.
For now i can load my game manually. but please see what you can do to fix this

**Comment by innominata** [comment]
> The issue is even more fun when you use the 'continue' option. It starts your game in sandbox mode like it or else. For now i can load my game manually. but please see what you can do to fix this

Are you using version 2.7.5?

**Comment by kittle31** [comment]
yep 2.7.5  Thats the latest version that auto-updates from thunderstore

**Comment by innominata** [comment]
> 

I'm unable to replicate the problem
