### ISSUE TITLE
Error when going to another planet

### ISSUE THREAD

**Issue by wgeminiw** [Touhma/DSP_Plugins#181]
(discovering github, assuming it's the way to submit issue...)

Whenever I go to starmap and click on another planet I have an error msg, I can close it, but I'm not sure it would work well after that, does this msg matter?
![Dyson](https://user-images.githubusercontent.com/108146537/175608269-794bdef2-8cc4-4339-bb7c-05232f3db3dc.png)

Best

**Comment by innominata** [comment]
Thats a new one.
Can you provide more info? What versions youre running?
Are you on discord?

**Comment by innominata** [comment]
Good to hear its sorted :D
