### ISSUE TITLE
Most recent GalacticScale version (2.7.7) causes game to red error on startup

### ISSUE THREAD

**Issue by Umbrasong** [Touhma/DSP_Plugins#183]
![image](https://user-images.githubusercontent.com/12302653/178972760-602e4aa4-8c68-41cd-a64c-e8213e60ad9e.png)

I can provide save file if desired, and I am using a significant number of other mods, if that has any effect

**Comment by innominata** [comment]
Is that mod manager profile from R2 or TMM ?
It wont load in R2 :)

**Comment by innominata** [comment]
It actually looks like this might a galacticscale issue, have you tried removing DSPOptimizations?
The error is being thrown by that mod, and its patching a method that GS doesn't touch.
Either that or try downgrading GS to 2.7.6 and see if it works again?
