### ISSUE TITLE
Logistics bot stats set to zero

### ISSUE THREAD

**Issue by dougtreder** [Touhma/DSP_Plugins#185]
Started a new game with Galactic Scale Mod 2.8.0. game v 0.9.27.14553.   After researching the new Logistics Bots and building them, their speed is set to zero.   Confirmed with new save both in sandbox and non-sandbox. 

extra details:

--------------

Researching upgrades does improve the stats, I think - each level increases capacity by 1, so you get capacity 1 after 1 level of research.  (In vanilla, it starts at 3 and should improve to 4).  

However, the speed starts at 0, and since research improves it 10%, it stays at zero even after two levels of research.  The bots start on their way but do not appear on screen and never arrive at Icarus.

Confirmed it also happened when starting in sandbox mode, getting common techs and common items (speed is 0, no items delivered).
![20220929170338_1](https://user-images.githubusercontent.com/628756/193162738-1209a694-8bfa-43be-a724-45ef97a6bc16.jpg)

However, when I loaded an old save made last week with previous version Galactic Scale, and researched the Logistics Bots, they behaved as expected with nonzero speed!

**Comment by innominata** [comment]
Fixed in 2.8.1 (Hopefully)
