### ISSUE TITLE
Logistics bots fly strangely on planets of non-normal sizes

### ISSUE THREAD

**Issue by Crowfooted** [Touhma/DSP_Plugins#186]
On telluric planets smaller than vanilla size, bots fly in a tall arch to reach their destination. Have not tested on large planets though.

**Comment by innominata** [comment]
Shouldn't be a difficult fix, thanks

**Comment by innominata** [comment]
impossible fix unfortunately, they are all in shader too. I raised a suggestion in the dsp discord if you want to upvote it
https://discord.com/channels/750553061369577492/801263634164219924/1028934174675046441
