### ISSUE TITLE
Advanced miner renders beams at wrong height on planets of non-normal size

### ISSUE THREAD

**Issue by Crowfooted** [Touhma/DSP_Plugins#187]
[Example on small planet](https://i.imgur.com/R79MaTB.jpeg)

**Comment by innominata** [comment]
Visual issue due to compiled shaders, nothing we can do unfortunately. And not for a lack of trying :)

**Comment by Crowfooted** [comment]
In lieu of moving the beams, would it be easier to just remove them or is that equally impossible?

**Comment by innominata** [comment]
Thats a really good idea, wish I'd thought of it :) I'll give it a go!
