### ISSUE TITLE
[BUG] Exception while trying to mass delete a belt place holder

### ISSUE THREAD

**Issue by riddles8888** [Touhma/DSP_Plugins#2]
If you place a long line of belts and then attempt to delete the place holder before your drones have built them then you will get an exception in game.

![image](https://user-images.githubusercontent.com/1985998/106924833-7d3eb800-66dd-11eb-9168-604400ef3c94.png)
![image](https://user-images.githubusercontent.com/1985998/106925096-c1ca5380-66dd-11eb-882f-4488c2884b58.png)

**Comment by riddles8888** [comment]
In the second picture if you attempt to mass delete a yellow segment you get the error in the first screen shot.

**Comment by Touhma** [comment]
Alright, nice catch ! I'll look into it :)

**Comment by MMZTimeLord** [comment]
I have also encountered this bug, but I do not have CopyInserters enabled. Has this been tried in the vanilla game? May be a vanilla bug.

**Comment by Touhma** [comment]
Qol is offically deprecated : someone did better : https://dsp.thunderstore.io/package/brokenmass/MultiDestruct/
