### ISSUE TITLE
Mod issues

### ISSUE THREAD

**Issue by ranmas** [Touhma/DSP_Plugins#23]
Other than the starting planet issues here are things I've seen.

1.  Planet sizes can be too small.   The smaller planet sizes causes graphical issues with the atmosphere in game.  Planet sizes need to be at least around 120 to keep this from happening.   Minimum planet size probably should be closer to 200.
My current settings:
BaseTelluricSize = 330
MinTelluricSize = 180
MaxTelluricSize = 480
BaseTelluricSizeVariationFactor = 150

HabitableRadiusAreaBaseline = 0.4
.4au is probably way to small.   A result of 1.0 - 1.2 au would probably be a better end result for a habitable zone.  Depending on the orbits available a bigger value may be needed.  This number probably should also vary depending on the star type.

2.  When loading a saved game buildings are below ground level and now underwater on smaller planets.  On Larger planets the ground goes to space.   Not sure at what size this changes.  Building near them does cause the ground to 'reset', however this happens every load, and there are other issues attached to this.

3.  Attached to the above issue Foundations do not work correctly.  When using them the grid that appears to be effected is not the grid under the mouse.  Also when placing foundation it does not graphically update the planet surface even if you do get or spend the soil.  Foundations will also cause the ground to fall away or rise into the sky like buildings on load.

4.  The mod causes the game to not change the name of the systems.  Every game now has the same name on the starting system.

One thing I find kind of odd is the max number of planets.  This doesn't seem to generate a range of planets.  The game seems to always generate the maximum number of planets available.  At least in the starting system it does.

For a fairly interesting looking g system I've been using:
7,5,1,0.4,1,0.6,0.8,0.6,0.6,0.3

Thank you for the mod.

**Comment by Touhma** [comment]
Alright that is a good report :) thanks a lot ! 

1 --> do you have a seed with the default config where the small planets bug appear ? 
2 --> I think it should be fixed in 0.0.9 
3 --> the foundation don't show in 0.0.9 but at least the buildings are showned
4 --> wut ? I'll look into that

thanks for the suggestion i'll dig into it :)

**Comment by ranmas** [comment]
You don't need a seed to test this.  Just a working save will do.  Change the config to just force the smallest planet size and load a save.  Planet sizes will adjust to the new size...  mind you any buildings will remain at the old planet size.  But on planets with a atmosphere you will see that the atmosphere 'glow' only covers a rectangular area, and that area doesn't properly cover the planet.  Exiting and changing back the config will restore the planets to their previous size.  

I can generate some seeds if you need.  But editing the config file to force tiny planets is just as easy. I will upload some screenshots when I get back to my pc.

**Comment by ranmas** [comment]
![glow 1](https://user-images.githubusercontent.com/7015459/108641364-e9a31080-746c-11eb-8493-66b01161a6bb.jpg)
![glow 2](https://user-images.githubusercontent.com/7015459/108641366-eb6cd400-746c-11eb-89ec-1b678096312d.jpg)
![glow seed](https://user-images.githubusercontent.com/7015459/108641367-ec056a80-746c-11eb-9a56-7276590978c1.jpg)
The seed 02081978 for the atmosphere glow issue on small planets.

![name 1](https://user-images.githubusercontent.com/7015459/108641368-ed369780-746c-11eb-9926-192df7d8c8ff.jpg)
![name 2](https://user-images.githubusercontent.com/7015459/108641371-ee67c480-746c-11eb-9bb9-774bbbdb3c39.jpg)
![name](https://user-images.githubusercontent.com/7015459/108641373-ef98f180-746c-11eb-8243-1c5876f7c100.jpg)
And as you can see all the home systems have the same name.

**Comment by Touhma** [comment]
yeah for the names i'm aware of that --> lemme see for the athmospheric bug 

It's not gameplay breaking but don't look nice I agree

**Comment by Touhma** [comment]
The atmosphere bug should be fixed with 1.0.10 Can you confirm ?

**Comment by ranmas** [comment]
Yeah, 1.0.10 fixed the atmosphere bug!

**Comment by ranmas** [comment]
Yeah, 1.0.10 fixed the atmosphere bug
![Desktop Screenshot 2021 02 21 - 19 33 51 10](https://user-images.githubusercontent.com/7015459/108644145-ce8bcd00-747b-11eb-9437-f1deacf0cdb8.png)
man size 80 planets are small

**Comment by Touhma** [comment]
yeah that's the main point :D 
creating new challenges with variability

**Comment by innominata** [comment]
> The atmosphere bug should be fixed with 1.0.10 Can you confirm ?
v1.1.2
![Untitled-11](https://user-images.githubusercontent.com/4099099/109778771-17a50380-7c6a-11eb-9d55-f52c8c567b21.jpg)
