### ISSUE TITLE
Low priority bug reports on seed 0268 8311, esp. starter platform not spawning

### ISSUE THREAD

**Issue by cBrenDev** [Touhma/DSP_Plugins#24]
Seed: 0268 8311
Config: all default, 64 planets
Skipped prologue (but confirmed that doesn't cause the starter platform issue on the known-good seed 49003102)

Issue 1: Starter platform didn't spawn
It looks like my starting planet is quite small, and the landing area looks like the terrain was manually adjusted (probably flattened) to meet requirements, but in doing so the starting platform never spawned.
![starterZone](https://user-images.githubusercontent.com/24590110/108648807-187baf80-748a-11eb-8259-127feddd6e0d.png)

Issue 2: Ores spawning inside terrain
Not a major issue, they're still mineable. Might even happen occasionally on vanilla if I'm honest. Might be related to issue 1, though. Note that the game seems to have some confusion about the terrain level here, see the screenshots "before" and "after" to see evidence that the terrain is modelled as if it's flat, shaded as if the mecha is in a crater, and recognized as raised (granting soil pile) when placing buildings.
![after](https://user-images.githubusercontent.com/24590110/108648798-174a8280-748a-11eb-8f9e-6154a03a9583.png)
![before](https://user-images.githubusercontent.com/24590110/108648800-17e31900-748a-11eb-95c3-854483557fb6.png)

Issue 3: Satellite confusion
Starter system has: my planet, with 2 satellites of its own; gas giant, with 1 satellite
Starter planet does not indicate it has satellites
Both starter planet moons indicate they are satellites in their tooltips
Gas giant has only 1 satellite, but tooltip claims it has plural satellites
![starterPlanet](https://user-images.githubusercontent.com/24590110/108648806-187baf80-748a-11eb-83b4-550e89e964c0.png)
![starterMoon](https://user-images.githubusercontent.com/24590110/108648805-187baf80-748a-11eb-8294-8a975deac6c2.png)
![multSatellites](https://user-images.githubusercontent.com/24590110/108648804-187baf80-748a-11eb-8324-a79c166c1f75.png)
![otherMoon](https://user-images.githubusercontent.com/24590110/108648802-187baf80-748a-11eb-837b-d73ab05d52be.png)

**Comment by Touhma** [comment]
Very good report, thanks for reporting this way :) 

Indeed i'll consider the moons confusion as a bug & the terrain shadows etc ... is considered as a temporary fix

The flattening function is acting weird sometime i need to find the reason why

**Comment by Touhma** [comment]
should be fixed now - reopen if needed

**Comment by Touhma** [comment]
Everything should be fixed in 1.3.0
