### ISSUE TITLE
GalacticScale 1.10 - plural satellite issues

### ISSUE THREAD

**Issue by Flipull** [Touhma/DSP_Plugins#27]
BepInEx + Thouma GalacticScale Plugin, no other mods

Game Seed 3440 5065, all default settings (64 solar systems, 1x multiplier, default generated config-file by r2-modmanager)

Starting Solar system contains a ice-giant (Vouskiaho - II ) with 1 moon ((Vouskiaho - II - I). Game says this moon has plural satellites. Orbit of the other moons show/imply those are satellite of the ice-giant, even though the ice-giant does not show the 'plural satellite' attribute. May be a visual bug only.

**Comment by Touhma** [comment]
should be fixed now - reopen if needed
