### ISSUE TITLE
[Nice to have] Notes on decompilation

### ISSUE THREAD

**Issue by brotchie** [Touhma/DSP_Plugins#3]
Awesome work Touhma, really impressed by how "patchable" Unity is, the code for the patches are fairly self-descriptive.

Do you have any notes you could dump in a markdown file (or bottom of the README) detailing your steps to understanding the game internals?

- Did you decompile the binary? If so, what tool did you use?
- Do you have a solution for interactive debugging?
- What does your write-eval-test loop look like, are you recompiling, starting up DSP, waiting for it to load, trying your patch? Or have you setup some kind of live debugging loop where you can on-the-fly inject your patch so you don't have to wait for DSP to start?

**Comment by MitoG** [comment]
Not Touhma but also doing modding:

> Did you decompile the binary? If so, what tool did you use?
.Net is relativley decompiler friendly, you can look at the code of .Net applications, which unity games are part of, with [ILSpy ](https://github.com/icsharpcode/ILSpy) or [DnSpy](https://github.com/dnSpy/dnSpy)

> Do you have a solution for interactive debugging?

Don't exactly know i what context.

Interactivley debugging the game ?

There is a way to enable debugging on a released Unity game where you replace a dll file with a modified one.

Interactivley debugging the mod?

I haven't found a way yet, might be different for Touhma.

> What does your write-eval-test loop look like, are you recompiling, starting up DSP, waiting for it to load, trying your patch? 

That's the way I do it. DSP is rather fast to load which doesn't make it more of a hassle than it could be on an unoptimized game.
There are modloaders that support hotloading mods. But I don't know if it could work for DSP.

**Comment by Touhma** [comment]
@brotchie Hey man,

To add on top of @MitoG : 

I'm currently using Jetbrains Rider to Code & compile the plugin, 
To see the source code of DSP i'm using DotPeek ( still jetbrains ) and I have a a private repo with the source code decompiled but kept private for personal usage for obvious legal reasons. 

To patch the game i'm using BepinEx & harmony allowing me with c# reflexion to replace some in game functions. 
To debug interractively ... unfortunately not that much exist you can come on the modding discord for DSP to get some help to get started if you want. 

For you third question : yep that's the most used solution so far unfortunately ... at least until we get official mods support :)
