### ISSUE TITLE
All buildings on starting planet have "Need foundation support" with default custom planet sizes

### ISSUE THREAD

**Issue by Radsterman** [Touhma/DSP_Plugins#33]
I've had this issue with every starting planet across multiple generations. It is tied solely to changing planet size because disabling that feature leaves every other part of this mod working.

I'm also encountering "Out of Building Range" for all buildings on some of them.

**Comment by GlitchHound** [comment]
We cannot replicate this issue on our end.

Are you using other mods? We've heard reports of this issue in conjunction with other mods, and at this time the use of our mod with others is At Your Own Risk as we aren't stable enough to spend time on cross-mod compatibility issues.

Specifically, we last saw this bug reported by someone who eventually determined the conflict was with Advanced Miners.

**Comment by Touhma** [comment]
Definitely a problem with an another mod : copy inserter for example have this problem.
