### ISSUE TITLE
Starting Planet - Strange behavior of Belts and even Water Pumps

### ISSUE THREAD

**Issue by Sherkhan-1** [Touhma/DSP_Plugins#34]
Starting planet - due to randomness I started with a Large one.
1. When placing belts over water - well, they cause the land to fill in underneath them
2. When placing water pumps - same issue land fills in under and around them
3. Had a very hard time landing on the planet after heading to another - I would get close to the ground and teleport way back up into the sky again. Only managed by hitting the alt key at just the right time.

**Comment by Touhma** [comment]
1 -> good point definitely an issue on our side 
2 -> Same 
3 -> Need some testing

Thanks for the report

**Comment by Sherkhan-1** [comment]
Of note, that save I posted for the other issue is the same as this issue - fyi

**Comment by Touhma** [comment]
Can you try again post 1.3.0 and reopen if still hapenning ?

**Comment by Sherkhan-1** [comment]
I will take a look in the morning for sure!
