### ISSUE TITLE
Another one - moon of gas giant

### ISSUE THREAD

**Issue by Sherkhan-1** [Touhma/DSP_Plugins#36]
![image](https://user-images.githubusercontent.com/79462670/109398797-e20fbb80-78f3-11eb-8ac9-45734607a2f6.png)

This was a nice belt of wind mills and a mining outpost - now after a save and then reload, everything looks like this.

**Comment by Touhma** [comment]
holy fuck 
xD

**Comment by Touhma** [comment]
Can you share your save file here ?

**Comment by Sherkhan-1** [comment]
[Wacked Planet 001a.zip](https://github.com/Touhma/DSP_Plugins/files/6055658/Wacked.Planet.001a.zip)

Here is the file, of note you will have to fly to the planet that exhibits this behavior. Small moon orbiting a gas giant (or frozen giant, I forget which).

**Comment by GlitchHound** [comment]
Just to be totally clear, were you using this mod when you first made the
save, or are you loading an existing save after freshly installing the mod?

**Comment by Sherkhan-1** [comment]
Nope - started a brand new play through with this mod from the get-go.

**Comment by Touhma** [comment]
alright 
We might have a fix for it coming soon 
hang on !

**Comment by AmahaShadow** [comment]
Same bug (probably),
When I jumped back to my home system, I got the big bad red message, and well, screenshot attached

![image](https://user-images.githubusercontent.com/66038459/109428869-39e41a80-79f9-11eb-9eee-e756c2aead59.png)

**Comment by AmahaShadow** [comment]
ps : reloading the game fixed the graphical bug for me, so maybe not the same issue ?
pps:  1.1.2

**Comment by ThePhoenix007** [comment]
I've had a similar issue, however, it seems to only occur where i've placed items.  Had the ground in a perfect little belt line, then where all my miners and smelters were.

**Comment by ThePhoenix007** [comment]
And another one.  All where I've built things.  This occured when leaving the planet and coming back.  Maybe something to do with LOD?
![20210228183721_1](https://user-images.githubusercontent.com/7071396/109437698-39955080-79f4-11eb-8eaa-635337680a33.jpg)

**Comment by ThePhoenix007** [comment]
To note, Saving and reloading the game (Didn't exit the game) fixes the issue, until you leave the planet and come back.

**Comment by Sherkhan-1** [comment]
well, saving and reloading certainly did not fix my issue though.

**Comment by Touhma** [comment]
should be fixed in 1.3.0

**Comment by Sherkhan-1** [comment]
Well, the save did not survive whatever the fix is - hehe... Here is what the home planet looks like now (note: The pretty lights in space was my research, and other factory stuff)
![image](https://user-images.githubusercontent.com/79462670/110254629-c8e6ba80-7f44-11eb-9366-83e49342ec7c.png)
