### ISSUE TITLE
really weird behaviour of planet after 5 hours in game

### ISSUE THREAD

**Issue by tramwajg** [Touhma/DSP_Plugins#42]
unplayable after 5 hours, weird terrain shading and planets surface going upward or downward significantly (foundations were fixing it, but it happens every time after leaving planet), can't land on some planets, I uninstalled 1.0.12 and installed 1.0.1 for more stars and this works fine, 1.0.1 seems like great work so far, my computer with 16core and rtx 3080 slows down;D I like this quantity and variety of systems it gives

![moon1](https://user-images.githubusercontent.com/78556223/109736792-3604f380-7bc5-11eb-9715-a06016f77fa1.png)
![moon2](https://user-images.githubusercontent.com/78556223/109736794-369d8a00-7bc5-11eb-8c40-5f6843882444.png)

**Comment by Touhma** [comment]
that should hopefully be fixed after the next release
