### ISSUE TITLE
Missing planet labels

### ISSUE THREAD

**Issue by Gc85** [Touhma/DSP_Plugins#44]
Found a glitch where some systems do not display the planet label names. Found an O-Type star system with 10 planets, yet only the first 6 labels are showing and the rest are not, so flying at Warp or Sail mode makes it very difficult to spot unless you are very close to the planet and can actually spot it.

![20210303222008_1](https://user-images.githubusercontent.com/22216984/109816257-e16c8180-7c73-11eb-8102-82ee6484509c.jpg)
Screenshot of system.

![20210303222204_1](https://user-images.githubusercontent.com/22216984/109816283-e6313580-7c73-11eb-80ca-b1cfbb09192c.jpg)
Left side shows star and planets close to it, right side shows planets and no labels.

**Comment by Touhma** [comment]
Seed : 62685338

**Comment by innominata** [comment]
I was unaware this was an unknown glitch :) Seconded. I'm pretty good at piloting via map now

**Comment by GlitchHound** [comment]
This was resolved alongside the ILS investigation, fix will be in the next release.
