### ISSUE TITLE
GalacticScale - mod compatibility build issue with non standard planet size

### ISSUE THREAD

**Issue by batty80** [Touhma/DSP_Plugins#45]
When installing Galactic Scale and any other mods have had issue with planet size.
With a larger default size planet and using any mod like copyinserters or advanced miner, i get the error "Need Foundation support" or "out of building range".
After changing the galactic-scale-planets-size>EnableResizingFeature=False, I can then construct buildings.
![20210304155024_1](https://user-images.githubusercontent.com/9602279/109913047-5b971780-7d01-11eb-9578-0595b2591143.jpg)

![20210304154609_1](https://user-images.githubusercontent.com/9602279/109912966-37d3d180-7d01-11eb-9ce5-bd12c1cd89e2.jpg)

**Comment by GlitchHound** [comment]
Hi there, thanks for the report!


This is a known issue and we do not claim to offer any cross-mod
compatibility at this time.

That said, stay tuned for new releases. There's a very good chance this
particular issue is resolved in the next release.

**Comment by GlitchHound** [comment]
Again, can't claim all cross-mod compatibility is resolved, but we've seen significant improvements with the new release!

**Comment by Touhma** [comment]
can you try again with 1.3.0 should be better
