### ISSUE TITLE
Icarus teleporting into sky when exiting sail mode

### ISSUE THREAD

**Issue by TheSonace** [Touhma/DSP_Plugins#46]
Icarus seems to teleport into the sky and drop to ground level a few times after exiting sail mode. More than likely related to the alternate planet sizes. This has happened on multiple planets.

**Comment by innominata** [comment]
It's part of the fun! And yes, I can reproduce this on large planets. Small ones seem to be the opposite where its hard to get into sail mode. (Maybe the game expects your altitude to be higher in order to enable?)

**Comment by Touhma** [comment]
Yeah there are still some issue on that, hopefully the next release will help with it.

**Comment by Touhma** [comment]
If you could test again when we release 1.3.0 could be nice :)
