### ISSUE TITLE
When entering a new system the game crashes sometimes

### ISSUE THREAD

**Issue by TheSonace** [Touhma/DSP_Plugins#48]
No screenshot of error unfortunately. When switching from lightyears to AU it starts to get laggy as well until the system is loaded properly. Might be the same issue.

**Comment by Touhma** [comment]
Hey there, what version are you on ?

**Comment by TheSonace** [comment]
This was version 1.1.2

**Comment by Touhma** [comment]
try again with 1.3.0 :) and open it again if it was not fixed
