### ISSUE TITLE
Beta 1.1.2.1 Does not Load Mod

### ISSUE THREAD

**Issue by kawika98** [Touhma/DSP_Plugins#49]
Today, I have switched the mod file with the beta mod file. This allows me to load in the save with no errors but removes all the mod's modifications.

**Comment by mola-ali** [comment]
hi, when it's gonna be fixed?
I wanted to start a new game and noticed the starting system doesn't go as planned in cfg file

**Comment by Touhma** [comment]
humm what you mean : remove all the mod's modificcations ?
can you be more specific ?

**Comment by mola-ali** [comment]
I'm sorry, it's my first time running this mod. I can't really say what's wrong with it. I just changed starting and other system numbers and planet size and didn't see any changes from normal play

**Comment by Touhma** [comment]
1.3.0 out :)
