### ISSUE TITLE
Hosting on SpaceDock.info

### ISSUE THREAD

**Issue by V1TA5** [Touhma/DSP_Plugins#5]
Hi,
after playing DysonSphere for several days now (without getting much sleep) i found the same shortcomings your mod fixes as you obviously did.

I do run a non profit mod hosting site for Kerbal Space Program as an hobby.
If i made an DysonsSphere Section would you be willing to upload your mod releases there too? 

Thanks again for your Work in making a mod before there are modding tools. :)

**Comment by Razunter** [comment]
There is also https://dsp.thunderstore.io/package/ with lots of mods.

**Comment by V1TA5** [comment]
Thank you. Didn't even know that existed.

**Comment by V1TA5** [comment]
Followup question: I couldnt find the License your mod is under.

**Comment by Touhma** [comment]
Any examples of license that can be used for this kind of mod ?

**Comment by jefair2** [comment]
Github has a nice little tool to help you figure out which license you should use here:
https://choosealicense.com/

And their documentation on Licensing a repo is here:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
