### ISSUE TITLE
[BUG]1.1.2.1->1.13

### ISSUE THREAD

**Issue by xibok** [Touhma/DSP_Plugins#50]
![image](https://user-images.githubusercontent.com/37209971/110226733-98932200-7f2c-11eb-8b45-cb0c04596885.png)

**Comment by GlitchHound** [comment]
Hi xibok, thanks for the report.

We can't reproduce this and there have been no other reports. That log doesn't look much like anything I've _ever_ seen the game produce, even in dev builds of this mod.

Are you running any other mods alongside this? It might be an incompatibility we haven't explored before.

**Comment by Touhma** [comment]
Yeah I don't think it's from us ...
don't seem like any methods we are touching
