### ISSUE TITLE
Missed detection of resource nodes on small planets

### ISSUE THREAD

**Issue by GlitchHound** [Touhma/DSP_Plugins#51]
Originally mentioned by GhostReaper on Discord, replicated by me.

Seed: 56549442
System: Vouskiaho (starter)
Planet: I-I
Radius: 100 (indicated by RuntimeUnityEditor)
Severity: Significant, but can be worked around

Sometimes, resource nodes will not be detected by miners, so that even if they are in the mining range they are not actually "reached" by the miner. In an extreme case, this means a miner cannot be built, citing "needs resources" even though they are present.
![unreachableNodes](https://user-images.githubusercontent.com/1190167/110246512-dea0b380-7f35-11eb-85be-e0694fc59d75.jpg)

Rotating or repositioning the miner may cause it to update and reach those otherwise unreachable nodes. Snapping-to-grid (rotation OR placement) does not inherently result in a better result. 
![sameNodesDetected](https://user-images.githubusercontent.com/1190167/110246668-80c09b80-7f36-11eb-9809-d858997049c9.jpg)

The problem in this case gets worse the further you move from the poles. The first instance of it I captured was with resource nodes on the 11th latitude band (screenshot: where the shift-to-accelerate tip starts). Note the error box is unrelated, it's from the F12 debugging tools.
![firstInstanceFromPole](https://user-images.githubusercontent.com/1190167/110246446-a0a38f80-7f35-11eb-95a3-f3f630f5d80b.jpg)

Even at the equator of this planet, the problem was present. It is unaffected by the presence or lack of foundations.
![equatorPatch](https://user-images.githubusercontent.com/1190167/110246553-0263f980-7f36-11eb-8cfd-aedcd89d7a9d.png)

The problem seems consistently replicable once you hit the affected latitudes. It happened with 0 of 4 polar veins tested, and with 3 of 3 with latitudes starting at the 11th band.

**Comment by Touhma** [comment]
My guess on that is that because of the curve of the planet... the miner don't detect the nodes because the base of the ressource node is a bit lower than the detection line

**Comment by GlitchHound** [comment]
I like that theory but I think the first two screenshots debunk it. Screenshot two shows the left two nodes being missed, so apparently the right two nodes are at the right height and the left ones are not. But then when we move further left of those two nodes (screenshot 1) they're still not visible.

**Comment by innominata** [comment]
It's not the curvature as far as I can tell, I've moved that collider around and up and down and still can't target the veins that arent targetable (until I move the miner over some threshold, that then changes which nodes are targetable)

**Comment by innominata** [comment]
Fixed
