### ISSUE TITLE
[Bug] Icarus Scaling after viewing other planets

### ISSUE THREAD

**Issue by MMZTimeLord** [Touhma/DSP_Plugins#52]
**Description:** After viewing another planet in system view and escaping back to normal game mode. Icarus is scaled up or down depending upon the last planet being viewed.

**Steps to replicate:**
1. Start a new game any seed with Galactic Scale set with Fixed Planetary Scaling (default)
2. Skip Prolog and walk off platform.
3. Press "V" to go to system view and click on ANY planet larger or smaller (Gas Giant has the most obvious results)
4. Press "Esc" to return to your home planet and normal view.
5. View your wonderfully scaled Icarus in all it's glory!

**Comment by MMZTimeLord** [comment]
![image](https://user-images.githubusercontent.com/48738604/110252989-d8620580-7f3c-11eb-8aaf-8ff112b148c7.png)
![image](https://user-images.githubusercontent.com/48738604/110253034-0c3d2b00-7f3d-11eb-90b2-4a23d3378ab2.png)

**Comment by innominata** [comment]
More of a feature than a bug
I know how to fix this, but should I?
GameMain.mainPlayer.transform.localScale = Vector3.one;
Usually only happens when teleporting...

**Comment by Suyashtnt** [comment]
> More of a feature than a bug
> I know how to fix this, but should I?
> GameMain.mainPlayer.transform.localScale = Vector3.one;
> Usually only happens when teleporting...

f i x

sure its funny but its just... annoying for the 2nd time

**Comment by innominata** [comment]
Should be fixed in 2.0
