### ISSUE TITLE
Unwanted ocean deletion

### ISSUE THREAD

**Issue by Thief-of-Time** [Touhma/DSP_Plugins#55]
When I place any structure near a liquid, the natural smoothing of planet surface to plane 0 affects said liquid as well. Meaning that anything placed near a liquid's edge will delete some of said liquid. This includes water extractors, placing them at the edge of a beach will make them stand in the moddle of a blob of solid land protruding into where there was water before but now isn't.

**Comment by Touhma** [comment]
![image](https://user-images.githubusercontent.com/8696405/111054782-5478b380-843d-11eb-885e-73e3665609f1.png)
Cannot reproduce it on my side ...

**Comment by Thief-of-Time** [comment]
Still happens, found out it only happens when "EnableResizingFeature" is set to "true".
