### ISSUE TITLE
New weird issue - not major just strange

### ISSUE THREAD

**Issue by Sherkhan-1** [Touhma/DSP_Plugins#57]
I have left the home system, going back and forth, So far when warping back, every time it goes from 20 or so AU out to 10-20 or so AU past the system in an instant. Could be this mod, could be others but it is a strange behavior :) - loving the mod. Using the new planet types mod as well, and after the latest update from you, the starting planet went from giant forest to giant icy forest - I doubt that is on your side though, but was interesting to load in, find myself in space then get to the planet and find it iced over- hehe.

**Comment by Sherkhan-1** [comment]
Bit more strangeness:
Before foundation
![image](https://user-images.githubusercontent.com/79462670/110928421-b4efdf80-82db-11eb-9ba7-48d560976812.png)
After returning a bunch of areas are slightly under the terrain - again, not sure where it came from
After foundation
![image](https://user-images.githubusercontent.com/79462670/110928550-dd77d980-82db-11eb-8093-614376374ae5.png)

**Comment by innominata** [comment]
Are you using the default config?

**Comment by Sherkhan-1** [comment]
Yep, have not changed or modified a thing with the config.

**Comment by Touhma** [comment]
Yeah there was definitely something happening with the biomes and probably because I fixed the gas giant so it's 100% on the last update :D

**Comment by Touhma** [comment]
Do you have swap of biomes when you reload again the game ?

**Comment by Sherkhan-1** [comment]
yeah - I did. Otherwise everything is working just fine, I just found it strange is all. All subsequent save and load has gone just fine. Makes sense.
