### ISSUE TITLE
Lightning is weird

### ISSUE THREAD

**Issue by AkiyamaAsuna** [Touhma/DSP_Plugins#6]
Lighting is weird on at least the starting planet.
On bright side of the planet, terrain is dark but vegetation/rocks are normal.
On dark side of the planet, terrain is bright but vegetation/rocks are normal.
Cluster 43370258-1024-A10
Planet is: Denebola I

![Screenshot_105](https://user-images.githubusercontent.com/47742123/108248777-91aa9800-7154-11eb-836e-2d96a3dab248.png)
![Screenshot_106](https://user-images.githubusercontent.com/47742123/108248778-92dbc500-7154-11eb-94d9-85f502069612.png)

**Comment by Touhma** [comment]
Should be fixed in the next patch :)
