### ISSUE TITLE
After 1.3.1 update, starter planet changed to an arid desert

### ISSUE THREAD

**Issue by Amadeus99** [Touhma/DSP_Plugins#63]
Not sure what the actual original type was for my starter planet, but it had water all over the place and was lush and green.  Now it is an arid desert and all the water is gone.  The trees are still there.  I attached a screen shot showing this.  Any way to revert the planet to its original type?

Let me know if you need any more information.  Thanks.

Edit: Forgot to mention that when I loaded up the save, I was in space and not on my planet where I did the save.

![20210312182123_1](https://user-images.githubusercontent.com/10092688/111016098-d47d1b80-8360-11eb-88f3-0f2e3b966465.jpg)

**Comment by innominata** [comment]
I'd suggest you downgrade your mod version to 1.3.0.
This mod isn't version safe yet, sometimes it loads fine, sometimes you are in another part of the galaxy and your planet is completely different. 
Hopefully the main part of the mod will be completed soon and won't need to break things when it changes

**Comment by Touhma** [comment]
Not really a bug , the saves are not cross version compatible yet
