### ISSUE TITLE
Error Report From Clicking On Planet, pics and save file attached

### ISSUE THREAD

**Issue by slinkletter** [Touhma/DSP_Plugins#65]
I was viewing the planets in my starter system in Starmap mode, working my way out from the center of the solar system.  When I clicked on VII-I, the game gave an error.  I am only using the 1.3.1 BETA mod and the Icarus recolor mod.  Config files are as generated by the spreadsheet with the values set as it came to me.

![1 3 1 Error clicked on satellite of VII](https://user-images.githubusercontent.com/47759979/111035992-932d5000-83e2-11eb-9a0e-e9d621c32893.jpg)
![Mods for 1 3 1 Error Report](https://user-images.githubusercontent.com/47759979/111036049-e43d4400-83e2-11eb-8faf-29443a4f2744.jpg)
[1.3.1 BETA 1024 Galaxy 19531940.dsv.zip](https://github.com/Touhma/DSP_Plugins/files/6135077/1.3.1.BETA.1024.Galaxy.19531940.dsv.zip)

It also happens when clicking on the satellites of the other planets beyond VII.  Satellites of planets VI and below do not give the error.  The central planets beyond VII do not give the error.

**Comment by innominata** [comment]
I think I may have solved this one, testing now

**Comment by innominata** [comment]
This is fixed in my latest PR

**Comment by innominata** [comment]
Fixed in 1.3.2
