### ISSUE TITLE
Weird blue haze/block

### ISSUE THREAD

**Issue by AkiyamaAsuna** [Touhma/DSP_Plugins#7]
Noticed it when i zoomed in but you can also see it in the screenshots from my other issue posted.
There's a blue haze/block in the screen that isn't there without the mod active

![Screenshot_108](https://user-images.githubusercontent.com/47742123/108248984-c9b1db00-7154-11eb-9610-d897ee8824cf.png)

**Comment by Touhma** [comment]
It should be fixed, re open if you still have the issue :)
