### ISSUE TITLE
Error while entering any system since patch .5972

### ISSUE THREAD

**Issue by kekegav2** [Touhma/DSP_Plugins#74]
Since today's patch I started getting this error whenever I enter any system.
Error: https://steamcommunity.com/sharedfiles/filedetails/?id=2429492752
Mod list: https://i.gyazo.com/5389672f7c76a65f1bd58a49fa6c848b.png

I can't tell if this is an incompatibility between mods, the mod or the game, or any combination. Do you think this could be related to your mod or is it something else? 

PS Love your mod and can't play without it. Too bad max stars is kinda laggy so I sticked to 512. 
PS2 Is it expected that some systems are empty? Have 2 black holes nearby (20 and 25ly) that have 0 planets.

**Comment by innominata** [comment]
Fixed in 1.3.2
