### ISSUE TITLE
Vouskiaho

### ISSUE THREAD

**Issue by innominata** [Touhma/DSP_Plugins#78]
Starting planet seems to be stuck with this name

**Comment by innominata** [comment]
I believe it might be the name from the menu save. Curious.

**Comment by ab9rf** [comment]
See [line 12 of ReworkStarGen.cs](https://github.com/Touhma/DSP_Plugins/blob/e71b45804df3c1e05570f4f454daa95f76192b1c/DSP_Plugins.GalacticScale/Scripts/PatchStarSystemGeneration/Rework/ReworkStarGen.cs#L12) (from commit 25f4bbdb); that's forcing the rename of every star based on its star index. "Vouskiaho" is simply the name in index position 0, which is always the index of the starting star. It's also forcing the names of every other star to match the list in SystemNames.cs, entirely dumping the randomly generated names.

**Comment by innominata** [comment]
> See [line 12 of ReworkStarGen.cs](https://github.com/Touhma/DSP_Plugins/blob/e71b45804df3c1e05570f4f454daa95f76192b1c/DSP_Plugins.GalacticScale/Scripts/PatchStarSystemGeneration/Rework/ReworkStarGen.cs#L12) (from commit [25f4bbd](https://github.com/Touhma/DSP_Plugins/commit/25f4bbdb6c3d50cc48f2ba050d824e57536e0681)); that's forcing the rename of every star based on its star index. "Vouskiaho" is simply the name in index position 0, which is always the index of the starting star. It's also forcing the names of every other star to match the list in SystemNames.cs, entirely dumping the randomly generated names.

I like you. 

Thanks! I'll sort that tonight

**Comment by innominata** [comment]
Oh yeah, this wasn't a bug 🤣
