### ISSUE TITLE
Updated from 1.0.1 to 1.0.3 and can no longer load an older save that used the older version of the mod

### ISSUE THREAD

**Issue by jefair2** [Touhma/DSP_Plugins#8]
Looks like a version incompatibility since this galaxy was generated off version 1.0.1.

![image](https://user-images.githubusercontent.com/42381266/108262667-361be280-7133-11eb-9adf-93510e6d2cef.png)

I noticed this is an issue as well if you try and load up a galaxy pre-mod when it was generated under the base game. Since the galaxy has already been generated off whichever mod, it would be nice if this could somehow be worked around. Otherwise I'll need to basically keep running an older version of your awesome mod, until I get tired of this save :(

**Comment by jefair2** [comment]
Just to be clear, the game simply won't load at all when there is an incompatibility like this, it just freezes up on the loading screen with this error.

Thankfully, any save can be loaded assuming you are running the version of the mod that you generated that galaxy with (or a save that was generated without this mod by removing the mod entirely/disabling it). Unfortunately there isn't a way to know (unless you named your saves appropriately) what version of the mod you were running for that save...

**Comment by Touhma** [comment]
Yep  ... do not use it with an existing save it's useless anyway ^^ 
I'll take report only from new games. and yes it will break saves IMO for now ... still have some issues here and there

**Comment by jefair2** [comment]
I realize it is useless in an existing save, what I was saying was it would be nice to not break the old ones. If there is anything I could provide or do to help resolve that, please let me know :D
