### ISSUE TITLE
[1.3.2] Moons are bigger than their planets

### ISSUE THREAD

**Issue by JJoschy** [Touhma/DSP_Plugins#81]
In the config, EnableMoonSizeFailSafe is true

<a href="https://www.bilder-upload.eu/bild-50322f-1616586094.jpg.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/50322f-1616586094.jpg" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

<a href="https://www.bilder-upload.eu/bild-e98552-1616586150.jpg.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/e98552-1616586150.jpg" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

**Comment by innominata** [comment]
That shouldn't happen. Can you attach your dsp.galactic-scale.planet-size.cfg ?

**Comment by JJoschy** [comment]
I have deletet the config files (because of the name changes of the file), start a new game, exiting it, then make my config changes (just in the star generation file).

[dsp.galactic-scale.planet-size.zip](https://github.com/Touhma/DSP_Plugins/files/6202508/dsp.galactic-scale.planet-size.zip)

**Comment by innominata** [comment]
I've figured it out, we are checking to see if the moon is bigger than the planet, and then making the moon the size smaller than the planet. If the planet is already the smallest size, it wont do anything. Will be fixed in next update, but will break saves.

**Comment by innominata** [comment]
Fixed in 1.4
