### ISSUE TITLE
game crash/error when warping away from home system

### ISSUE THREAD

**Issue by SimplifyAndAddCoffee** [Touhma/DSP_Plugins#82]
![20210325024654_1](https://user-images.githubusercontent.com/59942458/112454251-b971ba80-8d15-11eb-8932-a83255439b70.jpg)

I've tried warping away in the direction of multiple different nearby stars but always get the same error after a couple seconds at warp. :(

**Comment by Shad0wlife** [comment]
Do you use v1.3.1? Then you have to update but be aware that 1.3.2 breaks saves because planet sizes changed. Consult the discord server for that if possible.

**Comment by SimplifyAndAddCoffee** [comment]
> Do you use v1.3.1? Then you have to update but be aware that 1.3.2 breaks saves because planet sizes changed. Consult the discord server for that if possible.

of yeah I'm using 1.3.1 from r2modman

no way to salvage my save? I'm really far along in this game.

**Comment by innominata** [comment]
You could always compile the backcompat1.3.1 branch and use that :)
Or get discord, whichever's easier for you I guess. 
It's not guaranteed to fix anything, but it's worked for a couple of people

**Comment by innominata** [comment]
You can try this, its completely untested. Don't blame me if your pc turns inside out.
[GalacticScale1.3.1Hotfix.zip](https://github.com/Touhma/DSP_Plugins/files/6209018/GalacticScale1.3.1Hotfix.zip)

**Comment by SimplifyAndAddCoffee** [comment]
> You can try this, its completely untested. Don't blame me if your pc turns inside out.
> [GalacticScale1.3.1Hotfix.zip](https://github.com/Touhma/DSP_Plugins/files/6209018/GalacticScale1.3.1Hotfix.zip)
hey sounds exciting so fuck it, thanks! Will post results.

**Comment by SimplifyAndAddCoffee** [comment]
> You can try this, its completely untested. Don't blame me if your pc turns inside out.
> [GalacticScale1.3.1Hotfix.zip](https://github.com/Touhma/DSP_Plugins/files/6209018/GalacticScale1.3.1Hotfix.zip)

ok so dumb question.... is there a way I can import this in r2modman?

**Comment by innominata** [comment]
replace the dll in C:\Users\{username}\AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\profiles\{profilename}\BepInEx\plugins\{galacticscaledirectory} with the one from that zip
